{% set name = "nqlib" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nqlib-{{ version }}.tar.gz
  sha256: 1b05784634eef1a04120512aaf2f601fe7ee4ae0311fb6ed597fd6d27790e8f2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - pip
  run:
    - python >=3.8
    - numpy
    - scipy
    - slycot
    - control
    - cvxpy

test:
  imports:
    - nqlib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/knttnk/NQLib
  summary: 'NQLib: Library to design noise shaping quantizer for discrete-valued input control.'
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - knttnk
