{% set name = "nqlib" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1b05784634eef1a04120512aaf2f601fe7ee4ae0311fb6ed597fd6d27790e8f2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - control
    - cvxpy
    - slycot

test:
  imports:
    - nqlib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/knttnk/NQLib
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'NQLib: Library to design noise shaping quantizer for discrete-valued input control.'

extra:
  recipe-maintainers:
    - knttnk
