{% set name = "nqlib" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nqlib-{{ version }}.tar.gz
  sha256: 3d52584af46cb6a4577999eeb450bcfec0a15950f458e4844bf49f17ed99aa57

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - slycot
    - control
    - cvxpy

test:
  imports:
    - nqlib
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/knttnk/NQLib
  summary: 'NQLib: Library to design noise shaping quantizer for discrete-valued input control.'
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - knttnk
